services:
  hestia-database:
    image: 'postgres:12-alpine'
    container_name: 'hestia-database'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hestia
      POSTGRES_PASSWORD: test123
      