name: Deployment

on:
    push:
        branches:
            - main
jobs:
    deploy-app:
        name: Deploy App
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.GITHUB_SERVER_URL }}
                  username: ${{ env.GITHUB_REPOSITORY_OWNER }}
                  password: ${{ secrets.NPM_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: git.palko.ca/${{ env.GITHUB_REPOSITORY }}:latest
    deploy-storybook:
        name: Deploy Storybook
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.GITHUB_SERVER_URL }}
                  username: ${{ env.GITHUB_REPOSITORY_OWNER }}
                  password: ${{ secrets.NPM_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  file: Dockerfile.storybook
                  tags: git.palko.ca/${{ env.GITHUB_REPOSITORY }}-storybook:latest
