name: PR Gate
on:
    pull_request:
        branches: ['*']
jobs:
    checks:
        name: Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Bun Setup
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install
              run: bun install
            - name: Test
              run: bun test
            - name: Build
              run: bun run build
            - name: Prisma Schema Check
              run: bun prisma:validate
