name: PR Gate
on:
    pull_request:
        branches: ['*']
jobs:
    checks:
        name: Checks
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Bun Setup
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version-file: '.tool-versions'
            - name: Install
              run: bun install
            - name: Lint
              run: bun lint
            - name: Test
              run: bun test
            - name: Build
              run: bun run build
            - name: Svelte Check
              run: bun check
            - name: Prisma Check
              run: bun prisma:validate
